name: json_rpc_client
description: Dart library to write JSON RPC v1 and v2 clients
version: 1.0.2
repository: https://github.com/tejainece/json_rpc_client

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.11
